
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:80"  # Вы можете оставить это, чтобы тестировать приложение отдельно, но Nginx будет использовать внутреннюю связь
    restart: always
    networks:
      - admin_network


networks:
  admin_network:
    external: true
