name: Deploy to Server

on:
  push:
    branches: [main, stage, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Production
        if: github.ref_name == 'main'
        run: ssh -o StrictHostKeyChecking=no -t ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd apps/admin-panel && git pull origin main && docker compose down  && docker compose up --build -d"

      - name: Deploy to Development
        if: github.ref_name == 'dev'
        run: ssh -o StrictHostKeyChecking=no -t ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd apps/admin-panel-dev && git pull origin dev && docker compose down && docker compose up --build -d"
      - name: Deploy to Stage
        if: github.ref_name == 'stage'
        run: ssh -o StrictHostKeyChecking=no -t ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd apps/admin-panel-stage && git pull origin stage && docker compose down && docker compose up --build -d"

  notify:
    name: 📬 Telegram Notify
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    steps:
      - name: 📬 Telegram Notification
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          REF_NAME="${{ github.ref_name }}"
          SHA="${{ github.sha }}"
          AUTHOR="${{ github.event.head_commit.author.name }}"
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          DEPLOY_STATUS="${{ needs.deploy.result }}"

          if [ "$DEPLOY_STATUS" != "success" ]; then
            STATUS="🛑 *Ошибка деплоя*"
            EXTRA_LINK="\n\n[🔍 Открыть GitHub Actions]($RUN_URL)"
          else
            STATUS="✅ Деплой *успешен*"
            EXTRA_LINK=""
          fi

          CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}"

          TEXT="${STATUS}

          📦 *Ветка:* \`$REF_NAME\`
          🔖 *Тег:* \`$SHA\`
          👤 *Автор деплоя:* [$AUTHOR](https://github.com/$AUTHOR)
          📝 *Коммит:* $COMMIT_MESSAGE${EXTRA_LINK}"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d parse_mode=Markdown \
            -d "text=$TEXT"
